# Generated by Django 3.2.9 on 2021-11-18 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='media/alerte', verbose_name='photo de la scène')),
                ('description', models.CharField(max_length=70, verbose_name='description alerte')),
                ('telephone', models.CharField(max_length=50, verbose_name='telephone de la source')),
                ('date', models.DateField(verbose_name='date alerte')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, verbose_name='nom de la categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil', models.FileField(upload_to='media/profil', verbose_name='photo de profil')),
                ('sexe', models.CharField(choices=[('homme', 'homme'), ('femme', 'femme'), ('autre', 'autre')], max_length=10, verbose_name='sexe utilisateur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='media/publication', verbose_name='photo de la scène')),
                ('contenu', models.TextField(verbose_name='contenu de la publication')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.utilisateur', verbose_name='auteur de la publication')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categorie', verbose_name='categorie de la publication')),
            ],
        ),
        migrations.CreateModel(
            name='Commntaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='contenu du commentaire')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.utilisateur', verbose_name='auteur du commentaire')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.publication', verbose_name='publication')),
            ],
        ),
    ]
