# Generated by Django 3.2.9 on 2021-11-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211118_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='lieu',
            field=models.CharField(max_length=90, null=True, verbose_name='lieu'),
        ),
        migrations.AddField(
            model_name='publication',
            name='titre',
            field=models.CharField(max_length=50, null=True, verbose_name='titre de la publication'),
        ),
    ]
